### Fetch All Groups (New User)
GET http://localhost:5000/all-groups
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Fetch All Groups (Developer Test Example)
GET http://localhost:5000/all-groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4



### Send Join Request to a Group (New User)
POST http://localhost:5000/all-groups/group-join-requests
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

{
  "groupID": 1
}

### Send Join Request to a Group (Developer Test Example)
POST http://localhost:5000/all-groups/group-join-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4

{
  "groupID": 1
}



### Fetch User Group Statuses (New User)
GET http://localhost:5000/all-groups/user-status?userID=<replace_with_user_id>
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Fetch User Group Statuses (Developer Test Example)
GET http://localhost:5000/all-groups/user-status?userID=7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4



### Cancel Join Request (New User)
DELETE http://localhost:5000/all-groups/1/cancel-request
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Cancel Join Request (Developer Test Example)
DELETE http://localhost:5000/all-groups/1/cancel-request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4