### Fetch Favorite Groups (New User)
GET http://localhost:5000/favorites?userID=<replace_with_user_id>
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Fetch Favorite Groups (Developer Test Example)
GET http://localhost:5000/favorites?userID=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4



### Add a New Favorite Group (New User)
POST http://localhost:5000/favorites
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

{
  "userID": 1,
  "name": "My Favorite Movies"
}

### Add a New Favorite Group (Developer Test Example)
POST http://localhost:5000/favorites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4

{
  "userID": 1,
  "name": "Sci-Fi Favorites"
}



### Fetch Movies in a Specific Favorite Group - For Logged User (New User)
GET http://localhost:5000/favorites/movies/1
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Fetch Movies in a Specific Favorite Group - For Logged User (Developer Test Example)
GET http://localhost:5000/favorites/movies/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4



### Fetch Favorite Groups with Movie Counts (New User)
GET http://localhost:5000/favorites/with-movie-count/1
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Fetch Favorite Groups with Movie Counts (Developer Test Example)
GET http://localhost:5000/favorites/with-movie-count/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4



### Update Favorite Group Name (New User)
PUT http://localhost:5000/favorites/1
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

{
  "name": "Updated Group Name"
}

### Update Favorite Group Name (Developer Test Example)
PUT http://localhost:5000/favorites/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4

{
  "name": "My Updated Favorites"
}



### Delete a Favorite Group (New User)
DELETE http://localhost:5000/favorites/1
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Delete a Favorite Group (Developer Test Example)
DELETE http://localhost:5000/favorites/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4


### Fetch Movies in a Specific Favorite Group- For Non Logged User (New User)
GET http://localhost:5000/favorites/public/1
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

### Fetch Movies in a Specific Favorite Group - For Non Logged User (Developer Test Example)
GET http://localhost:5000/favorites/public/1
Content-Type: application/json


