### Send Join Request to a Group (New User)
POST http://localhost:5000/group-join-requests
Content-Type: application/json
Authorization: Bearer <replace_with_auth_token>

{
  "userID": 1,
  "groupID": 2
}

### Send Join Request to a Group (Developer Test Example)
POST http://localhost:5000/group-join-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjcsImVtYWlsIjoiUnlhbjFAMTIzIiwiZmlyc3RuYW1lIjoiUiIsImxhc3RuYW1lIjoiRCIsImNpdHkiOiJUYW1wZXJlIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTczMzg2NDAzMCwiZXhwIjoxNzMzODY3NjMwfQ.Prk5TYtclO0JC5T7U0NEBaMmrFrPimMZ3XVmesv1sJ4

{
  "userID": 1,
  "groupID": 1
}
