# Register User 1
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "Password123",
    "firstName": "Ryan",
    "lastName": "Wick",
    "city": "Helsinki"
}

### Register User with Invalid password (no capital letter or number)
POST http://localhost:5000/register
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "password123",
  "firstName": "Alice",
  "lastName": "Smith",
  "city": "Espoo"
}


### Register User 2
POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "anotheruser@example.com",
    "password": "AnotherPassword123",
    "firstName": "Jane",
    "lastName": "Doe",
    "city": "Espoo"
}





### Get All Registered Users
GET http://localhost:5000/register
Content-Type: application/json