### Get All Reviews
GET http://localhost:5000/reviews
Content-Type: application/json

### Get a Movie Review
GET http://localhost:5000/reviews?title=Wicked&releaseDate=2021
Content-Type: application/json

### Get Movie Reviews
GET http://localhost:5000/reviews?title=Red%20One&releaseDate=2023
Content-Type: application/json