# Test Sign-In with valid credentials
POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "Password123"
}



### Test Sign-In with invalid credentials (wrong password)
POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "wrongpassword"
}

### Test Sign-In with non-existing email
POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "nonexistent@example.com",
  "password": "randompassword"
}

### Test Sign-In with missing fields
POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "",
  "password": ""
}

